Could be a flag on the &lt;clustering ... /&gt; config element.  If set, the exception should not be re-thrown but simply logged.
